parameters:
- name: environmentObjects
  type: object
  default:
  - environmentName: 'dev'
    dependsOn: ''
    regionAbrvs: ['eus']
  - environmentName: 'tst'
    dependsOn: ''
    regionAbrvs: ['eus']
- name: templateFile
  type: string
  default: 'main'
- name: serviceName
  type: string
  default: 'spaado'
- name: npm_cache
  type: boolean
  default: true

stages:
- template: stages/terraform_js_build_stage.yml.yml@templates
  parameters:
    serviceName: ${{ parameters.serviceName }}
    environmentObjects: ${{ parameters.environmentObjects }}